name: Create Production Build
run-name: ${{ github.actor }} is creating production build
on: [push]
jobs:
  create-producion-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '20.10.0'
      - run: npm install
      - run: npm run build
